services:
  frontend:
    build:
      context: ./frontend
      args:
        VITE_UMAMI_URL: ${VITE_UMAMI_URL}
        VITE_UMAMI_WEBSITE_ID: ${VITE_UMAMI_WEBSITE_ID}
    ports:
      - '8742:80'
    depends_on:
      - backend

  backend:
    build: ./backend
    env_file:
      - .env
    environment:
      - PORT=8000
    expose:
      - '8000'
