services:
  frontend:
    build: ./frontend
    ports:
      - "8742:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    environment:
      - PORT=8000
    expose:
      - "8000"
